# -*- coding: utf-8 -*-
"""Task_1_Iris_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Max1AA49aTWvVXpW7xLiyxRPGNWQ_BB0

# **Organization: DevelopersHub Corporation**
# Author: Hifza Nazir
# Date: 10 February 2026

# **Task 1: Exploring and Visualizing the Iris Dataset**

# 1. Import Required Libraries
"""

import pandas as pd      # for handling data
import seaborn as sns    # for making graphs
import matplotlib.pyplot as plt # for customizing graphs

print("Libraries successfully imported!")

"""# 2. Load the Dataset"""

# Loading the inbuilt Iris dataset from seaborn library
df = sns.load_dataset('iris')

# Displaying the first five rows of the dataset
print("First 5 rows of the dataset:")
display(df.head())

"""# 3. Data Inspection and Summary Statistics"""

# Printing the shape of the dataset (Rows, Columns)
print(f"Dataset Shape: {df.shape}")

# Printing column names
print(f"\nColumn Names: {df.columns.tolist()}")

# Displaying dataset information (data types and null values)
print("\nDataset Info:")
df.info()

# Displaying summary statistics for numerical features
print("\nSummary Statistics:")
display(df.describe())

"""# 4. Data Visualization

A) Scatter Plot (To show relationships between features)
"""

# Creating a scatter plot to see the relationship between Sepal Length and Sepal Width
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='sepal_length', y='sepal_width', hue='species', style='species', s=100)
plt.title('Relationship between Sepal Length and Sepal Width')
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.legend(title='Species')
plt.show()

"""B) Histograms (To show value distributions)"""

# Plotting histograms for all numerical features to understand their distribution
df.hist(figsize=(12, 10), bins=15, edgecolor='black')
plt.suptitle('Distribution of Iris Features', fontsize=16)
plt.show()

"""C) Box Plots (To identify outliers)"""

# Creating box plots to compare feature distributions across different species
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x='species', y='petal_length')
plt.title('Petal Length Distribution by Species (Box Plot)')
plt.show()